### ISSUE TITLE
Harman - Finishing touches

### ISSUE THREAD

**Issue by kaminskg** [Take-Your-Money-Corp/not-avg-lifecoach#45]
- Have at least two short dialogues that show when your agent is not able to handle the conversation properly (screenshot 2 instances)
- Record any hours the group spent in meetings :

**Comment by Harman-Sahota** [comment]
**Have at least two short dialogues that show when your agent is not able to handle the conversation properly (screenshot 2 instances):**

![image](https://user-images.githubusercontent.com/56659047/110360490-c7acaf00-8064-11eb-9609-f08b5fdb8224.png)
![image](https://user-images.githubusercontent.com/56659047/110360502-caa79f80-8064-11eb-9115-f45611804754.png)

**Record any hours the group spent in meetings :**
**Meeting HOURS:**
G & D - Feb 10th - 0.5 hours
Feb 10th - 3 hours 
Feb 15th - 3 hours
Feb 17th - 3 hours
Feb 24 - 3 hours
March 1 - 2 hours
March 2  - 2 hours
G & D - Mar 4th - 1 hour
